/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Fish12(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/fish/fish_012.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play the 'idle_fish.012' animation if it exists
    if (actions["idle_fish.012"]) {
      actions["idle_fish.012"].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature_fish012" >
          <skinnedMesh
            name="fish012"
            geometry={nodes.fish012.geometry}
            material={materials.Material}
            skeleton={nodes.fish012.skeleton}
          />
          <primitive object={nodes.Bone005} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/fish/fish_012.glb");


